/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestesRouteImport } from './routes/testes'
import { Route as SobreOProjetoRouteImport } from './routes/sobre-o-projeto'
import { Route as ReferenciasRouteImport } from './routes/referencias'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as MapaInterativoRouteImport } from './routes/mapa-interativo'
import { Route as LinhaDoTempoRouteImport } from './routes/linha-do-tempo'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as EquipeDoProjetoRouteImport } from './routes/equipe-do-projeto'
import { Route as CreditosRouteImport } from './routes/creditos'
import { Route as ApoioFinanceiroRouteImport } from './routes/apoio-financeiro'
import { Route as AcessibilidadeRouteImport } from './routes/acessibilidade'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogDoConhecimentoIndexRouteImport } from './routes/blog-do-conhecimento/index'
import { Route as AlmanaqueDigitalIndexRouteImport } from './routes/almanaque-digital/index'
import { Route as BlogDoConhecimentoChar123SlugChar125RouteImport } from './routes/blog-do-conhecimento/{-$slug}'
import { Route as AlmanaqueDigitalGlossarioRouteImport } from './routes/almanaque-digital/glossario'

const TestesRoute = TestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreOProjetoRoute = SobreOProjetoRouteImport.update({
  id: '/sobre-o-projeto',
  path: '/sobre-o-projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenciasRoute = ReferenciasRouteImport.update({
  id: '/referencias',
  path: '/referencias',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaInterativoRoute = MapaInterativoRouteImport.update({
  id: '/mapa-interativo',
  path: '/mapa-interativo',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhaDoTempoRoute = LinhaDoTempoRouteImport.update({
  id: '/linha-do-tempo',
  path: '/linha-do-tempo',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeDoProjetoRoute = EquipeDoProjetoRouteImport.update({
  id: '/equipe-do-projeto',
  path: '/equipe-do-projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditosRoute = CreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoioFinanceiroRoute = ApoioFinanceiroRouteImport.update({
  id: '/apoio-financeiro',
  path: '/apoio-financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessibilidadeRoute = AcessibilidadeRouteImport.update({
  id: '/acessibilidade',
  path: '/acessibilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDoConhecimentoIndexRoute = BlogDoConhecimentoIndexRouteImport.update({
  id: '/blog-do-conhecimento/',
  path: '/blog-do-conhecimento/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanaqueDigitalIndexRoute = AlmanaqueDigitalIndexRouteImport.update({
  id: '/almanaque-digital/',
  path: '/almanaque-digital/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDoConhecimentoChar123SlugChar125Route =
  BlogDoConhecimentoChar123SlugChar125RouteImport.update({
    id: '/blog-do-conhecimento/{-$slug}',
    path: '/blog-do-conhecimento/{-$slug}',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlmanaqueDigitalGlossarioRoute =
  AlmanaqueDigitalGlossarioRouteImport.update({
    id: '/almanaque-digital/glossario',
    path: '/almanaque-digital/glossario',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/apoio-financeiro': typeof ApoioFinanceiroRoute
  '/creditos': typeof CreditosRoute
  '/equipe-do-projeto': typeof EquipeDoProjetoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/mapa-interativo': typeof MapaInterativoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/referencias': typeof ReferenciasRoute
  '/sobre-o-projeto': typeof SobreOProjetoRoute
  '/testes': typeof TestesRoute
  '/almanaque-digital/glossario': typeof AlmanaqueDigitalGlossarioRoute
  '/blog-do-conhecimento/{-$slug}': typeof BlogDoConhecimentoChar123SlugChar125Route
  '/almanaque-digital/': typeof AlmanaqueDigitalIndexRoute
  '/blog-do-conhecimento/': typeof BlogDoConhecimentoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/apoio-financeiro': typeof ApoioFinanceiroRoute
  '/creditos': typeof CreditosRoute
  '/equipe-do-projeto': typeof EquipeDoProjetoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/mapa-interativo': typeof MapaInterativoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/referencias': typeof ReferenciasRoute
  '/sobre-o-projeto': typeof SobreOProjetoRoute
  '/testes': typeof TestesRoute
  '/almanaque-digital/glossario': typeof AlmanaqueDigitalGlossarioRoute
  '/blog-do-conhecimento/{-$slug}': typeof BlogDoConhecimentoChar123SlugChar125Route
  '/almanaque-digital': typeof AlmanaqueDigitalIndexRoute
  '/blog-do-conhecimento': typeof BlogDoConhecimentoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessibilidade': typeof AcessibilidadeRoute
  '/apoio-financeiro': typeof ApoioFinanceiroRoute
  '/creditos': typeof CreditosRoute
  '/equipe-do-projeto': typeof EquipeDoProjetoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/linha-do-tempo': typeof LinhaDoTempoRoute
  '/mapa-interativo': typeof MapaInterativoRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/referencias': typeof ReferenciasRoute
  '/sobre-o-projeto': typeof SobreOProjetoRoute
  '/testes': typeof TestesRoute
  '/almanaque-digital/glossario': typeof AlmanaqueDigitalGlossarioRoute
  '/blog-do-conhecimento/{-$slug}': typeof BlogDoConhecimentoChar123SlugChar125Route
  '/almanaque-digital/': typeof AlmanaqueDigitalIndexRoute
  '/blog-do-conhecimento/': typeof BlogDoConhecimentoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessibilidade'
    | '/apoio-financeiro'
    | '/creditos'
    | '/equipe-do-projeto'
    | '/fale-conosco'
    | '/linha-do-tempo'
    | '/mapa-interativo'
    | '/politica-de-privacidade'
    | '/referencias'
    | '/sobre-o-projeto'
    | '/testes'
    | '/almanaque-digital/glossario'
    | '/blog-do-conhecimento/{-$slug}'
    | '/almanaque-digital/'
    | '/blog-do-conhecimento/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessibilidade'
    | '/apoio-financeiro'
    | '/creditos'
    | '/equipe-do-projeto'
    | '/fale-conosco'
    | '/linha-do-tempo'
    | '/mapa-interativo'
    | '/politica-de-privacidade'
    | '/referencias'
    | '/sobre-o-projeto'
    | '/testes'
    | '/almanaque-digital/glossario'
    | '/blog-do-conhecimento/{-$slug}'
    | '/almanaque-digital'
    | '/blog-do-conhecimento'
  id:
    | '__root__'
    | '/'
    | '/acessibilidade'
    | '/apoio-financeiro'
    | '/creditos'
    | '/equipe-do-projeto'
    | '/fale-conosco'
    | '/linha-do-tempo'
    | '/mapa-interativo'
    | '/politica-de-privacidade'
    | '/referencias'
    | '/sobre-o-projeto'
    | '/testes'
    | '/almanaque-digital/glossario'
    | '/blog-do-conhecimento/{-$slug}'
    | '/almanaque-digital/'
    | '/blog-do-conhecimento/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessibilidadeRoute: typeof AcessibilidadeRoute
  ApoioFinanceiroRoute: typeof ApoioFinanceiroRoute
  CreditosRoute: typeof CreditosRoute
  EquipeDoProjetoRoute: typeof EquipeDoProjetoRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  LinhaDoTempoRoute: typeof LinhaDoTempoRoute
  MapaInterativoRoute: typeof MapaInterativoRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ReferenciasRoute: typeof ReferenciasRoute
  SobreOProjetoRoute: typeof SobreOProjetoRoute
  TestesRoute: typeof TestesRoute
  AlmanaqueDigitalGlossarioRoute: typeof AlmanaqueDigitalGlossarioRoute
  BlogDoConhecimentoChar123SlugChar125Route: typeof BlogDoConhecimentoChar123SlugChar125Route
  AlmanaqueDigitalIndexRoute: typeof AlmanaqueDigitalIndexRoute
  BlogDoConhecimentoIndexRoute: typeof BlogDoConhecimentoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testes': {
      id: '/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof TestesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-o-projeto': {
      id: '/sobre-o-projeto'
      path: '/sobre-o-projeto'
      fullPath: '/sobre-o-projeto'
      preLoaderRoute: typeof SobreOProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referencias': {
      id: '/referencias'
      path: '/referencias'
      fullPath: '/referencias'
      preLoaderRoute: typeof ReferenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-interativo': {
      id: '/mapa-interativo'
      path: '/mapa-interativo'
      fullPath: '/mapa-interativo'
      preLoaderRoute: typeof MapaInterativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linha-do-tempo': {
      id: '/linha-do-tempo'
      path: '/linha-do-tempo'
      fullPath: '/linha-do-tempo'
      preLoaderRoute: typeof LinhaDoTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe-do-projeto': {
      id: '/equipe-do-projeto'
      path: '/equipe-do-projeto'
      fullPath: '/equipe-do-projeto'
      preLoaderRoute: typeof EquipeDoProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creditos': {
      id: '/creditos'
      path: '/creditos'
      fullPath: '/creditos'
      preLoaderRoute: typeof CreditosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoio-financeiro': {
      id: '/apoio-financeiro'
      path: '/apoio-financeiro'
      fullPath: '/apoio-financeiro'
      preLoaderRoute: typeof ApoioFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessibilidade': {
      id: '/acessibilidade'
      path: '/acessibilidade'
      fullPath: '/acessibilidade'
      preLoaderRoute: typeof AcessibilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-do-conhecimento/': {
      id: '/blog-do-conhecimento/'
      path: '/blog-do-conhecimento'
      fullPath: '/blog-do-conhecimento/'
      preLoaderRoute: typeof BlogDoConhecimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanaque-digital/': {
      id: '/almanaque-digital/'
      path: '/almanaque-digital'
      fullPath: '/almanaque-digital/'
      preLoaderRoute: typeof AlmanaqueDigitalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-do-conhecimento/{-$slug}': {
      id: '/blog-do-conhecimento/{-$slug}'
      path: '/blog-do-conhecimento/{-$slug}'
      fullPath: '/blog-do-conhecimento/{-$slug}'
      preLoaderRoute: typeof BlogDoConhecimentoChar123SlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanaque-digital/glossario': {
      id: '/almanaque-digital/glossario'
      path: '/almanaque-digital/glossario'
      fullPath: '/almanaque-digital/glossario'
      preLoaderRoute: typeof AlmanaqueDigitalGlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessibilidadeRoute: AcessibilidadeRoute,
  ApoioFinanceiroRoute: ApoioFinanceiroRoute,
  CreditosRoute: CreditosRoute,
  EquipeDoProjetoRoute: EquipeDoProjetoRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  LinhaDoTempoRoute: LinhaDoTempoRoute,
  MapaInterativoRoute: MapaInterativoRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ReferenciasRoute: ReferenciasRoute,
  SobreOProjetoRoute: SobreOProjetoRoute,
  TestesRoute: TestesRoute,
  AlmanaqueDigitalGlossarioRoute: AlmanaqueDigitalGlossarioRoute,
  BlogDoConhecimentoChar123SlugChar125Route:
    BlogDoConhecimentoChar123SlugChar125Route,
  AlmanaqueDigitalIndexRoute: AlmanaqueDigitalIndexRoute,
  BlogDoConhecimentoIndexRoute: BlogDoConhecimentoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
