/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpactoSocialRouteImport } from './routes/impacto-social'
import { Route as FaleConoscoRouteImport } from './routes/fale-conosco'
import { Route as EquipeDoProjetoRouteImport } from './routes/equipe-do-projeto'
import { Route as AgendaDoProjetoRouteImport } from './routes/agenda-do-projeto'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovoIndexRouteImport } from './routes/novo/index'
import { Route as FiquePorDentroIndexRouteImport } from './routes/fique-por-dentro/index'
import { Route as AlmanaqueDigitalIndexRouteImport } from './routes/almanaque-digital/index'
import { Route as FiquePorDentroChar123SlugChar125RouteImport } from './routes/fique-por-dentro/{-$slug}'
import { Route as ApiEmailRouteImport } from './routes/api/email'
import { Route as AlmanaqueDigitalVaAlemRouteImport } from './routes/almanaque-digital/va-alem'
import { Route as AlmanaqueDigitalMapaInterativoRouteImport } from './routes/almanaque-digital/mapa-interativo'
import { Route as AlmanaqueDigitalLinhaDoTempoRouteImport } from './routes/almanaque-digital/linha-do-tempo'
import { Route as AlmanaqueDigitalGlossarioRouteImport } from './routes/almanaque-digital/glossario'
import { Route as AlmanaqueDigitalCapituloChar123NumberChar125RouteImport } from './routes/almanaque-digital/capitulo-{-$number}'
import { Route as NovoAlmanaqueDigitalIndexRouteImport } from './routes/novo/almanaque-digital/index'
import { Route as AlmanaqueDigitalTesteDeConhecimentoIndexRouteImport } from './routes/almanaque-digital/teste-de-conhecimento/index'
import { Route as NovoAlmanaqueDigitalLinhaDoTempoRouteImport } from './routes/novo/almanaque-digital/linha-do-tempo'
import { Route as AlmanaqueDigitalTesteDeConhecimentoQuizRouteImport } from './routes/almanaque-digital/teste-de-conhecimento/quiz'

const ImpactoSocialRoute = ImpactoSocialRouteImport.update({
  id: '/impacto-social',
  path: '/impacto-social',
  getParentRoute: () => rootRouteImport,
} as any)
const FaleConoscoRoute = FaleConoscoRouteImport.update({
  id: '/fale-conosco',
  path: '/fale-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeDoProjetoRoute = EquipeDoProjetoRouteImport.update({
  id: '/equipe-do-projeto',
  path: '/equipe-do-projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaDoProjetoRoute = AgendaDoProjetoRouteImport.update({
  id: '/agenda-do-projeto',
  path: '/agenda-do-projeto',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoIndexRoute = NovoIndexRouteImport.update({
  id: '/novo/',
  path: '/novo/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiquePorDentroIndexRoute = FiquePorDentroIndexRouteImport.update({
  id: '/fique-por-dentro/',
  path: '/fique-por-dentro/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanaqueDigitalIndexRoute = AlmanaqueDigitalIndexRouteImport.update({
  id: '/almanaque-digital/',
  path: '/almanaque-digital/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiquePorDentroChar123SlugChar125Route =
  FiquePorDentroChar123SlugChar125RouteImport.update({
    id: '/fique-por-dentro/{-$slug}',
    path: '/fique-por-dentro/{-$slug}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmailRoute = ApiEmailRouteImport.update({
  id: '/api/email',
  path: '/api/email',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanaqueDigitalVaAlemRoute = AlmanaqueDigitalVaAlemRouteImport.update({
  id: '/almanaque-digital/va-alem',
  path: '/almanaque-digital/va-alem',
  getParentRoute: () => rootRouteImport,
} as any)
const AlmanaqueDigitalMapaInterativoRoute =
  AlmanaqueDigitalMapaInterativoRouteImport.update({
    id: '/almanaque-digital/mapa-interativo',
    path: '/almanaque-digital/mapa-interativo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlmanaqueDigitalLinhaDoTempoRoute =
  AlmanaqueDigitalLinhaDoTempoRouteImport.update({
    id: '/almanaque-digital/linha-do-tempo',
    path: '/almanaque-digital/linha-do-tempo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlmanaqueDigitalGlossarioRoute =
  AlmanaqueDigitalGlossarioRouteImport.update({
    id: '/almanaque-digital/glossario',
    path: '/almanaque-digital/glossario',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlmanaqueDigitalCapituloChar123NumberChar125Route =
  AlmanaqueDigitalCapituloChar123NumberChar125RouteImport.update({
    id: '/almanaque-digital/capitulo-{-$number}',
    path: '/almanaque-digital/capitulo-{-$number}',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovoAlmanaqueDigitalIndexRoute =
  NovoAlmanaqueDigitalIndexRouteImport.update({
    id: '/novo/almanaque-digital/',
    path: '/novo/almanaque-digital/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlmanaqueDigitalTesteDeConhecimentoIndexRoute =
  AlmanaqueDigitalTesteDeConhecimentoIndexRouteImport.update({
    id: '/almanaque-digital/teste-de-conhecimento/',
    path: '/almanaque-digital/teste-de-conhecimento/',
    getParentRoute: () => rootRouteImport,
  } as any)
const NovoAlmanaqueDigitalLinhaDoTempoRoute =
  NovoAlmanaqueDigitalLinhaDoTempoRouteImport.update({
    id: '/novo/almanaque-digital/linha-do-tempo',
    path: '/novo/almanaque-digital/linha-do-tempo',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlmanaqueDigitalTesteDeConhecimentoQuizRoute =
  AlmanaqueDigitalTesteDeConhecimentoQuizRouteImport.update({
    id: '/almanaque-digital/teste-de-conhecimento/quiz',
    path: '/almanaque-digital/teste-de-conhecimento/quiz',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/agenda-do-projeto': typeof AgendaDoProjetoRoute
  '/equipe-do-projeto': typeof EquipeDoProjetoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/impacto-social': typeof ImpactoSocialRoute
  '/almanaque-digital/capitulo-{-$number}': typeof AlmanaqueDigitalCapituloChar123NumberChar125Route
  '/almanaque-digital/glossario': typeof AlmanaqueDigitalGlossarioRoute
  '/almanaque-digital/linha-do-tempo': typeof AlmanaqueDigitalLinhaDoTempoRoute
  '/almanaque-digital/mapa-interativo': typeof AlmanaqueDigitalMapaInterativoRoute
  '/almanaque-digital/va-alem': typeof AlmanaqueDigitalVaAlemRoute
  '/api/email': typeof ApiEmailRoute
  '/fique-por-dentro/{-$slug}': typeof FiquePorDentroChar123SlugChar125Route
  '/almanaque-digital/': typeof AlmanaqueDigitalIndexRoute
  '/fique-por-dentro/': typeof FiquePorDentroIndexRoute
  '/novo/': typeof NovoIndexRoute
  '/almanaque-digital/teste-de-conhecimento/quiz': typeof AlmanaqueDigitalTesteDeConhecimentoQuizRoute
  '/novo/almanaque-digital/linha-do-tempo': typeof NovoAlmanaqueDigitalLinhaDoTempoRoute
  '/almanaque-digital/teste-de-conhecimento/': typeof AlmanaqueDigitalTesteDeConhecimentoIndexRoute
  '/novo/almanaque-digital/': typeof NovoAlmanaqueDigitalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/agenda-do-projeto': typeof AgendaDoProjetoRoute
  '/equipe-do-projeto': typeof EquipeDoProjetoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/impacto-social': typeof ImpactoSocialRoute
  '/almanaque-digital/capitulo-{-$number}': typeof AlmanaqueDigitalCapituloChar123NumberChar125Route
  '/almanaque-digital/glossario': typeof AlmanaqueDigitalGlossarioRoute
  '/almanaque-digital/linha-do-tempo': typeof AlmanaqueDigitalLinhaDoTempoRoute
  '/almanaque-digital/mapa-interativo': typeof AlmanaqueDigitalMapaInterativoRoute
  '/almanaque-digital/va-alem': typeof AlmanaqueDigitalVaAlemRoute
  '/api/email': typeof ApiEmailRoute
  '/fique-por-dentro/{-$slug}': typeof FiquePorDentroChar123SlugChar125Route
  '/almanaque-digital': typeof AlmanaqueDigitalIndexRoute
  '/fique-por-dentro': typeof FiquePorDentroIndexRoute
  '/novo': typeof NovoIndexRoute
  '/almanaque-digital/teste-de-conhecimento/quiz': typeof AlmanaqueDigitalTesteDeConhecimentoQuizRoute
  '/novo/almanaque-digital/linha-do-tempo': typeof NovoAlmanaqueDigitalLinhaDoTempoRoute
  '/almanaque-digital/teste-de-conhecimento': typeof AlmanaqueDigitalTesteDeConhecimentoIndexRoute
  '/novo/almanaque-digital': typeof NovoAlmanaqueDigitalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/agenda-do-projeto': typeof AgendaDoProjetoRoute
  '/equipe-do-projeto': typeof EquipeDoProjetoRoute
  '/fale-conosco': typeof FaleConoscoRoute
  '/impacto-social': typeof ImpactoSocialRoute
  '/almanaque-digital/capitulo-{-$number}': typeof AlmanaqueDigitalCapituloChar123NumberChar125Route
  '/almanaque-digital/glossario': typeof AlmanaqueDigitalGlossarioRoute
  '/almanaque-digital/linha-do-tempo': typeof AlmanaqueDigitalLinhaDoTempoRoute
  '/almanaque-digital/mapa-interativo': typeof AlmanaqueDigitalMapaInterativoRoute
  '/almanaque-digital/va-alem': typeof AlmanaqueDigitalVaAlemRoute
  '/api/email': typeof ApiEmailRoute
  '/fique-por-dentro/{-$slug}': typeof FiquePorDentroChar123SlugChar125Route
  '/almanaque-digital/': typeof AlmanaqueDigitalIndexRoute
  '/fique-por-dentro/': typeof FiquePorDentroIndexRoute
  '/novo/': typeof NovoIndexRoute
  '/almanaque-digital/teste-de-conhecimento/quiz': typeof AlmanaqueDigitalTesteDeConhecimentoQuizRoute
  '/novo/almanaque-digital/linha-do-tempo': typeof NovoAlmanaqueDigitalLinhaDoTempoRoute
  '/almanaque-digital/teste-de-conhecimento/': typeof AlmanaqueDigitalTesteDeConhecimentoIndexRoute
  '/novo/almanaque-digital/': typeof NovoAlmanaqueDigitalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/agenda-do-projeto'
    | '/equipe-do-projeto'
    | '/fale-conosco'
    | '/impacto-social'
    | '/almanaque-digital/capitulo-{-$number}'
    | '/almanaque-digital/glossario'
    | '/almanaque-digital/linha-do-tempo'
    | '/almanaque-digital/mapa-interativo'
    | '/almanaque-digital/va-alem'
    | '/api/email'
    | '/fique-por-dentro/{-$slug}'
    | '/almanaque-digital/'
    | '/fique-por-dentro/'
    | '/novo/'
    | '/almanaque-digital/teste-de-conhecimento/quiz'
    | '/novo/almanaque-digital/linha-do-tempo'
    | '/almanaque-digital/teste-de-conhecimento/'
    | '/novo/almanaque-digital/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/agenda-do-projeto'
    | '/equipe-do-projeto'
    | '/fale-conosco'
    | '/impacto-social'
    | '/almanaque-digital/capitulo-{-$number}'
    | '/almanaque-digital/glossario'
    | '/almanaque-digital/linha-do-tempo'
    | '/almanaque-digital/mapa-interativo'
    | '/almanaque-digital/va-alem'
    | '/api/email'
    | '/fique-por-dentro/{-$slug}'
    | '/almanaque-digital'
    | '/fique-por-dentro'
    | '/novo'
    | '/almanaque-digital/teste-de-conhecimento/quiz'
    | '/novo/almanaque-digital/linha-do-tempo'
    | '/almanaque-digital/teste-de-conhecimento'
    | '/novo/almanaque-digital'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/agenda-do-projeto'
    | '/equipe-do-projeto'
    | '/fale-conosco'
    | '/impacto-social'
    | '/almanaque-digital/capitulo-{-$number}'
    | '/almanaque-digital/glossario'
    | '/almanaque-digital/linha-do-tempo'
    | '/almanaque-digital/mapa-interativo'
    | '/almanaque-digital/va-alem'
    | '/api/email'
    | '/fique-por-dentro/{-$slug}'
    | '/almanaque-digital/'
    | '/fique-por-dentro/'
    | '/novo/'
    | '/almanaque-digital/teste-de-conhecimento/quiz'
    | '/novo/almanaque-digital/linha-do-tempo'
    | '/almanaque-digital/teste-de-conhecimento/'
    | '/novo/almanaque-digital/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AgendaDoProjetoRoute: typeof AgendaDoProjetoRoute
  EquipeDoProjetoRoute: typeof EquipeDoProjetoRoute
  FaleConoscoRoute: typeof FaleConoscoRoute
  ImpactoSocialRoute: typeof ImpactoSocialRoute
  AlmanaqueDigitalCapituloChar123NumberChar125Route: typeof AlmanaqueDigitalCapituloChar123NumberChar125Route
  AlmanaqueDigitalGlossarioRoute: typeof AlmanaqueDigitalGlossarioRoute
  AlmanaqueDigitalLinhaDoTempoRoute: typeof AlmanaqueDigitalLinhaDoTempoRoute
  AlmanaqueDigitalMapaInterativoRoute: typeof AlmanaqueDigitalMapaInterativoRoute
  AlmanaqueDigitalVaAlemRoute: typeof AlmanaqueDigitalVaAlemRoute
  ApiEmailRoute: typeof ApiEmailRoute
  FiquePorDentroChar123SlugChar125Route: typeof FiquePorDentroChar123SlugChar125Route
  AlmanaqueDigitalIndexRoute: typeof AlmanaqueDigitalIndexRoute
  FiquePorDentroIndexRoute: typeof FiquePorDentroIndexRoute
  NovoIndexRoute: typeof NovoIndexRoute
  AlmanaqueDigitalTesteDeConhecimentoQuizRoute: typeof AlmanaqueDigitalTesteDeConhecimentoQuizRoute
  NovoAlmanaqueDigitalLinhaDoTempoRoute: typeof NovoAlmanaqueDigitalLinhaDoTempoRoute
  AlmanaqueDigitalTesteDeConhecimentoIndexRoute: typeof AlmanaqueDigitalTesteDeConhecimentoIndexRoute
  NovoAlmanaqueDigitalIndexRoute: typeof NovoAlmanaqueDigitalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impacto-social': {
      id: '/impacto-social'
      path: '/impacto-social'
      fullPath: '/impacto-social'
      preLoaderRoute: typeof ImpactoSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fale-conosco': {
      id: '/fale-conosco'
      path: '/fale-conosco'
      fullPath: '/fale-conosco'
      preLoaderRoute: typeof FaleConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe-do-projeto': {
      id: '/equipe-do-projeto'
      path: '/equipe-do-projeto'
      fullPath: '/equipe-do-projeto'
      preLoaderRoute: typeof EquipeDoProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda-do-projeto': {
      id: '/agenda-do-projeto'
      path: '/agenda-do-projeto'
      fullPath: '/agenda-do-projeto'
      preLoaderRoute: typeof AgendaDoProjetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo/': {
      id: '/novo/'
      path: '/novo'
      fullPath: '/novo/'
      preLoaderRoute: typeof NovoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fique-por-dentro/': {
      id: '/fique-por-dentro/'
      path: '/fique-por-dentro'
      fullPath: '/fique-por-dentro/'
      preLoaderRoute: typeof FiquePorDentroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanaque-digital/': {
      id: '/almanaque-digital/'
      path: '/almanaque-digital'
      fullPath: '/almanaque-digital/'
      preLoaderRoute: typeof AlmanaqueDigitalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fique-por-dentro/{-$slug}': {
      id: '/fique-por-dentro/{-$slug}'
      path: '/fique-por-dentro/{-$slug}'
      fullPath: '/fique-por-dentro/{-$slug}'
      preLoaderRoute: typeof FiquePorDentroChar123SlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email': {
      id: '/api/email'
      path: '/api/email'
      fullPath: '/api/email'
      preLoaderRoute: typeof ApiEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanaque-digital/va-alem': {
      id: '/almanaque-digital/va-alem'
      path: '/almanaque-digital/va-alem'
      fullPath: '/almanaque-digital/va-alem'
      preLoaderRoute: typeof AlmanaqueDigitalVaAlemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanaque-digital/mapa-interativo': {
      id: '/almanaque-digital/mapa-interativo'
      path: '/almanaque-digital/mapa-interativo'
      fullPath: '/almanaque-digital/mapa-interativo'
      preLoaderRoute: typeof AlmanaqueDigitalMapaInterativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanaque-digital/linha-do-tempo': {
      id: '/almanaque-digital/linha-do-tempo'
      path: '/almanaque-digital/linha-do-tempo'
      fullPath: '/almanaque-digital/linha-do-tempo'
      preLoaderRoute: typeof AlmanaqueDigitalLinhaDoTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanaque-digital/glossario': {
      id: '/almanaque-digital/glossario'
      path: '/almanaque-digital/glossario'
      fullPath: '/almanaque-digital/glossario'
      preLoaderRoute: typeof AlmanaqueDigitalGlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanaque-digital/capitulo-{-$number}': {
      id: '/almanaque-digital/capitulo-{-$number}'
      path: '/almanaque-digital/capitulo-{-$number}'
      fullPath: '/almanaque-digital/capitulo-{-$number}'
      preLoaderRoute: typeof AlmanaqueDigitalCapituloChar123NumberChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo/almanaque-digital/': {
      id: '/novo/almanaque-digital/'
      path: '/novo/almanaque-digital'
      fullPath: '/novo/almanaque-digital/'
      preLoaderRoute: typeof NovoAlmanaqueDigitalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanaque-digital/teste-de-conhecimento/': {
      id: '/almanaque-digital/teste-de-conhecimento/'
      path: '/almanaque-digital/teste-de-conhecimento'
      fullPath: '/almanaque-digital/teste-de-conhecimento/'
      preLoaderRoute: typeof AlmanaqueDigitalTesteDeConhecimentoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo/almanaque-digital/linha-do-tempo': {
      id: '/novo/almanaque-digital/linha-do-tempo'
      path: '/novo/almanaque-digital/linha-do-tempo'
      fullPath: '/novo/almanaque-digital/linha-do-tempo'
      preLoaderRoute: typeof NovoAlmanaqueDigitalLinhaDoTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/almanaque-digital/teste-de-conhecimento/quiz': {
      id: '/almanaque-digital/teste-de-conhecimento/quiz'
      path: '/almanaque-digital/teste-de-conhecimento/quiz'
      fullPath: '/almanaque-digital/teste-de-conhecimento/quiz'
      preLoaderRoute: typeof AlmanaqueDigitalTesteDeConhecimentoQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AgendaDoProjetoRoute: AgendaDoProjetoRoute,
  EquipeDoProjetoRoute: EquipeDoProjetoRoute,
  FaleConoscoRoute: FaleConoscoRoute,
  ImpactoSocialRoute: ImpactoSocialRoute,
  AlmanaqueDigitalCapituloChar123NumberChar125Route:
    AlmanaqueDigitalCapituloChar123NumberChar125Route,
  AlmanaqueDigitalGlossarioRoute: AlmanaqueDigitalGlossarioRoute,
  AlmanaqueDigitalLinhaDoTempoRoute: AlmanaqueDigitalLinhaDoTempoRoute,
  AlmanaqueDigitalMapaInterativoRoute: AlmanaqueDigitalMapaInterativoRoute,
  AlmanaqueDigitalVaAlemRoute: AlmanaqueDigitalVaAlemRoute,
  ApiEmailRoute: ApiEmailRoute,
  FiquePorDentroChar123SlugChar125Route: FiquePorDentroChar123SlugChar125Route,
  AlmanaqueDigitalIndexRoute: AlmanaqueDigitalIndexRoute,
  FiquePorDentroIndexRoute: FiquePorDentroIndexRoute,
  NovoIndexRoute: NovoIndexRoute,
  AlmanaqueDigitalTesteDeConhecimentoQuizRoute:
    AlmanaqueDigitalTesteDeConhecimentoQuizRoute,
  NovoAlmanaqueDigitalLinhaDoTempoRoute: NovoAlmanaqueDigitalLinhaDoTempoRoute,
  AlmanaqueDigitalTesteDeConhecimentoIndexRoute:
    AlmanaqueDigitalTesteDeConhecimentoIndexRoute,
  NovoAlmanaqueDigitalIndexRoute: NovoAlmanaqueDigitalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
